eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_INSTANCE_LIST}
  server:
    enable-self-preservation: true
    response-cache-auto-expiration-in-seconds: 180
    response-cache-update-interval-ms: 10000
    eviction-interval-timer-in-ms: 10000